"""
LSTM-BEKK Model

Main implementation of the LSTM-BEKK model combining LSTM and BEKK components.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Union
import logging
from tqdm import tqdm

from .bekk_components import BEKKLayer
from .lstm_components import LSTMComponent, EnhancedLSTMComponent
from .model_utils import ModelUtils


class LSTMBEKKModel(nn.Module):
    """
    LSTM-BEKK Model Implementation
    
    Implements the hybrid model: H_t = CC' + C_t*C_t' + a*r_{t-1}*r_{t-1}' + b*H_{t-1}
    where C_t is generated by an LSTM network.
    """
    
    def __init__(self, n_assets: int, config: Optional[Dict] = None):
        """
        Initialize LSTM-BEKK model.
        
        Args:
            n_assets: Number of assets
            config: Model configuration dictionary
        """
        super().__init__()
        self.n_assets = n_assets
        self.config = config or self._get_default_config()
        self.logger = logging.getLogger(__name__)
        
        # Extract configuration
        lstm_config = self.config.get('lstm_bekk', {})
        
        # Initialize components
        self.bekk_layer = BEKKLayer(n_assets)
        
        # Choose LSTM component type
        if lstm_config.get('enhanced', False):
            self.lstm_component = EnhancedLSTMComponent(
                n_assets=n_assets,
                hidden_size=lstm_config.get('hidden_size', n_assets),
                num_layers=lstm_config.get('num_layers', 3),
                dropout=lstm_config.get('dropout', 0.2),
                use_attention=lstm_config.get('use_attention', True)
            )
        else:
            self.lstm_component = LSTMComponent(
                n_assets=n_assets,
                hidden_size=lstm_config.get('hidden_size', n_assets),
                num_layers=lstm_config.get('num_layers', 3),
                dropout=lstm_config.get('dropout', 0.2)
            )
        
        # Training state
        self.is_fitted = False
        self.training_history = []
        
    def forward(self, returns: torch.Tensor, 
                return_components: bool = False) -> Union[torch.Tensor, Tuple[torch.Tensor, Dict]]:
        """
        Forward pass of LSTM-BEKK model.
        
        Args:
            returns: Return vectors (T x n_assets)
            return_components: Whether to return individual components
            
        Returns:
            Conditional covariance matrices or (matrices, components)
        """
        T, n = returns.shape
        device = returns.device
        
        # Validate inputs
        ModelUtils.validate_inputs(returns)
        
        # Get BEKK covariance matrices (without dynamic component)
        H_bekk = self.bekk_layer(returns)  # (T x n x n)
        
        # Get dynamic component from LSTM
        C_dynamic, _ = self.lstm_component(returns[:-1])  # Use t-1 returns, shape: (T-1 x n x n)
        
        # Calculate dynamic covariance: C_t @ C_t'
        dynamic_cov = torch.matmul(C_dynamic, C_dynamic.transpose(-2, -1))  # (T-1 x n x n)
        
        # Combine components: H_t = H_bekk + C_t*C_t'
        H_combined = torch.zeros_like(H_bekk)
        H_combined[0] = H_bekk[0]  # First period uses only BEKK
        H_combined[1:] = H_bekk[1:] + dynamic_cov  # Add dynamic component from t=1
        
        # Ensure positive definiteness
        for t in range(T):
            H_combined[t] = ModelUtils.ensure_positive_definite(H_combined[t])
        
        if return_components:
            components = {
                'bekk_component': H_bekk,
                'dynamic_component': dynamic_cov,
                'combined': H_combined
            }
            return H_combined, components
        
        return H_combined
    
    def calculate_loss(self, returns: torch.Tensor) -> torch.Tensor:
        """
        Calculate negative log-likelihood loss.
        
        Args:
            returns: Return vectors
            
        Returns:
            Negative log-likelihood
        """
        # Get covariance matrices
        H = self.forward(returns)
        
        # Calculate negative log-likelihood
        nll = ModelUtils.negative_log_likelihood(returns[1:], H[1:])  # Skip first period
        
        return nll
    
    def fit(self, train_data: pd.DataFrame, 
            validation_data: Optional[pd.DataFrame] = None,
            epochs: int = None, 
            learning_rate: float = None,
            verbose: bool = True) -> Dict:
        """
        Fit the LSTM-BEKK model.
        
        Args:
            train_data: Training data (DataFrame with returns)
            validation_data: Validation data
            epochs: Number of training epochs
            learning_rate: Learning rate
            verbose: Whether to show progress
            
        Returns:
            Training history
        """
        self.logger.info("Starting LSTM-BEKK model training")
        
        # Extract configuration
        lstm_config = self.config.get('lstm_bekk', {})
        epochs = epochs or lstm_config.get('epochs', 100)
        learning_rate = learning_rate or lstm_config.get('learning_rate', 0.001)
        
        # Convert to tensors
        train_tensor = torch.tensor(train_data.values, dtype=torch.float32)
        val_tensor = None
        if validation_data is not None:
            val_tensor = torch.tensor(validation_data.values, dtype=torch.float32)
        
        # Setup optimizer
        optimizer = optim.RMSprop(self.parameters(), lr=learning_rate)
        scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            optimizer, mode='min', factor=0.5, patience=10, verbose=verbose
        )
        
        # Training loop
        self.training_history = []
        best_val_loss = float('inf')
        patience_counter = 0
        patience = lstm_config.get('early_stopping_patience', 10)
        
        for epoch in range(epochs):
            # Training phase
            self.train()
            train_loss = self.calculate_loss(train_tensor)
            
            # Backward pass
            optimizer.zero_grad()
            train_loss.backward()
            
            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(self.parameters(), max_norm=1.0)
            
            optimizer.step()
            
            # Validation phase
            val_loss = None
            if val_tensor is not None:
                self.eval()
                with torch.no_grad():
                    val_loss = self.calculate_loss(val_tensor)
                scheduler.step(val_loss)
            else:
                scheduler.step(train_loss)
            
            # Record history
            epoch_history = {
                'epoch': epoch,
                'train_loss': train_loss.item(),
                'val_loss': val_loss.item() if val_loss is not None else None,
                'learning_rate': optimizer.param_groups[0]['lr']
            }
            self.training_history.append(epoch_history)
            
            # Early stopping
            if val_loss is not None:
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    patience_counter = 0
                else:
                    patience_counter += 1
                    
                if patience_counter >= patience:
                    self.logger.info(f"Early stopping at epoch {epoch}")
                    break
            
            # Progress logging
            if verbose and (epoch + 1) % 10 == 0:
                log_msg = f"Epoch {epoch+1}/{epochs}, Train Loss: {train_loss.item():.6f}"
                if val_loss is not None:
                    log_msg += f", Val Loss: {val_loss.item():.6f}"
                self.logger.info(log_msg)
        
        self.is_fitted = True
        self.logger.info("Training completed")
        
        return self.training_history
    
    def predict_covariance(self, returns: pd.DataFrame, steps: int = 1) -> np.ndarray:
        """
        Predict future covariance matrices.
        
        Args:
            returns: Historical returns
            steps: Number of steps to forecast
            
        Returns:
            Predicted covariance matrices
        """
        if not self.is_fitted:
            raise ValueError("Model must be fitted before prediction")
        
        self.eval()
        with torch.no_grad():
            # Convert to tensor
            returns_tensor = torch.tensor(returns.values, dtype=torch.float32)
            
            # Get current state
            H_current = self.forward(returns_tensor)[-1]  # Last covariance matrix
            
            # For multi-step forecasting, we need to simulate forward
            # This is a simplified approach - in practice, you might want more sophisticated forecasting
            forecasts = []
            
            for step in range(steps):
                # Use unconditional forecast (zero returns assumption)
                # This could be enhanced with return forecasting models
                zero_returns = torch.zeros(1, self.n_assets)
                
                # Get BEKK forecast
                bekk_forecast = self.bekk_layer.predict_covariance(returns_tensor, steps=1)
                
                # For LSTM component, we'd need the return at t to predict C_{t+1}
                # Using zero returns as a simple approach
                C_dynamic, _ = self.lstm_component(zero_returns)
                dynamic_cov = torch.matmul(C_dynamic, C_dynamic.transpose(-2, -1))
                
                # Combine
                H_forecast = bekk_forecast[0] + dynamic_cov[0]
                H_forecast = ModelUtils.ensure_positive_definite(H_forecast)
                
                forecasts.append(H_forecast.numpy())
        
        return np.array(forecasts)
    
    def get_model_parameters(self) -> Dict:
        """Get model parameters and statistics."""
        if not self.is_fitted:
            raise ValueError("Model must be fitted first")
        
        # Get BEKK parameters
        bekk_params = {
            'a': self.bekk_layer.get_bekk_parameters()[0].item(),
            'b': self.bekk_layer.get_bekk_parameters()[1].item(),
            'C_static': self.bekk_layer.C.detach().numpy()
        }
        
        # Get LSTM parameters
        lstm_params = {
            'hidden_size': self.lstm_component.hidden_size,
            'num_layers': self.lstm_component.num_layers,
            'beta': self.lstm_component.beta.item()
        }
        
        return {
            'bekk_parameters': bekk_params,
            'lstm_parameters': lstm_params,
            'n_assets': self.n_assets,
            'is_fitted': self.is_fitted,
            'training_epochs': len(self.training_history) if self.training_history else 0
        }
    
    def _get_default_config(self) -> Dict:
        """Get default model configuration."""
        return {
            'lstm_bekk': {
                'hidden_size': self.n_assets,
                'num_layers': 3,
                'dropout': 0.2,
                'epochs': 100,
                'learning_rate': 0.001,
                'early_stopping_patience': 10,
                'enhanced': False,
                'use_attention': False
            }
        }
