from setuptools import setup, find_packages

setup(
    name="cubic-framework",
    version="1.0.0",
    description="CUBIC: Component fUsion and Binary encoding classIfication with Confidence for Stock Market Index Prediction",
    author="CUBIC Implementation",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.21.0",
        "pandas>=1.5.0",
        "scikit-learn>=1.2.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "xbbg>=0.7.0",
        "tqdm>=4.64.0",
        "pyyaml>=6.0",
        "ta>=0.10.0",
        "plotly>=5.0.0",
        "jupyter>=1.0.0",
        "ipykernel>=6.0.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
