%
scripts_run = {'S30_ON_M_com_subfactor1.m';'S30_ON_M_com_subfactor2.m';...
    'S30_ON_M_com_subfactor3.m';'S30_ON_M_com_subfactor4.m';'S30_ON_M_com_subfactor5.m';...
    'S30_ON_M_com_factor1.m';'S30_ON_M_com_factor2.m';'S30_ON_M_com_factor3.m';...
    'S30_ON_M_com_factor4.m';'S30_ON_M_com_factor5.m';...
    'S30_ON_M_com_factor_final.m';'S30_ON_M_com_factor_final_adj.m';...
    'S30_ON_M_com_factor_final_average.m';'S30_ON_output.m'};
T = length(scripts_run);
for i = 1:T
    title_str = sprintf('S30: step%d',i);
    order_str = scripts_run{i}(1:end-2);  
    run_program_adair(order_str,title_str);
end