dN = 'yuqerdata';
tn = 'yq_FdmtCFTTMPITGet';
var_info = {'secID', 'partyID', 'ticker', 'secShortName', 'exchangeCD', 'endDate',...
       'publishDate', 'isNew', 'isCalc', 'CFrSaleGS', 'NDeposIncrCFI',...
       'NIncrBorrFrCB', 'NIncBorrOthFI', 'premFrOrigContr', 'NReinsurPrem',...
       'NIncPhDeposInv', 'NIncDispTradFA', 'IFCCashIncr', 'NIncFrBorr',...
       'NCApIncrRepur', 'refundOfTax', 'CFrOthOperateA', 'CInfFrOperateA',...
       'CPaidGS', 'NIncDisburOfLA', 'NIncrDeposInFI', 'origContrCIndem',...
       'CPaidIFC', 'CPaidPolDiv', 'CPaidToForEmpl', 'CPaidForTaxes',...
       'CPaidForOthOpA', 'COutfOperateA', 'NCFOperateA', 'procSellInvest',...
       'gainInvest', 'dispFixAssetsOth', 'NDispSubsOthBizC', 'CFrOthInvestA',...
       'CInfFrInvestA', 'purFixAssetsOth', 'CPaidInvest', 'NIncrPledgeLoan',...
       'NCPaidAcquis', 'CPaidOthInvestA', 'COutfFrInvestA', 'NCFFrInvestA',...
       'CFrCapContr', 'CFrMinoSSubs', 'CFrBorr', 'CFrIssueBond',...
       'CFrOthFinanA', 'CInfFrFinanA', 'CPaidForDebts', 'CPaidDivProfInt',...
       'divProfSubsMinoS', 'CPaidOthFinanA', 'COutfFrFinanA', 'NCFFrFinanA',...
       'forexEffects', 'NChangeInCash', 'NCEBegBal', 'NCEEndBal'};
var_type = cell(size(var_info));
var_type(:) = {'float'};
var_type([1,3,4,5]) = {'varchar(20)'};
var_type([6,7]) = {'date'};
%key_var = {'symbol','tradingdate'};
key_var = strjoin(var_info([3,6,7]),',');
%key_var = var_info{1};
create_table_adair(dN,tn,var_info,var_type,key_var)